### ISSUE TITLE
How do I include these components?

### ISSUE THREAD

**Issue by Stubbs** [hailocab/react-pure#5]
I've installed react-pure via npm & when I try and include it in one of my components I get the following error:

```
ERROR in ./~/react-pure/src/Button.js
Module parse failed: /Users/stu/Projects/fluxible/node_modules/react-pure/src/Button.js Line 1: Unexpected reserved word
You may need an appropriate loader to handle this file type.

import React from 'react';
import classNames from 'classnames';

@ ./components/Home.jsx 3:17-49
```

I'm including it like this:

    var PureButton = require('react-pure/src/Button');

What's the right way to include these components in my project?

**Comment by Stubbs** [comment]
For reference here is the entire file:

```
'use strict';
var React = require('react');
var PureButton = require('react-pure/src/Button');

var Home = React.createClass({
    getInitialState: function () {
        return {};
    },
    render: function() {
        return (
            <div>
                <PureButton className="success">Success</PureButton>
                <PureButton className="error">Failed</PureButton>
            </div>
        );
    }
});

module.exports = Home;
```

It's just Home.js from a clean "yo fluxible" with react-pure installed via npm.

**Comment by Stubbs** [comment]
and finally a better stack trace:

```
/Users/stu/Projects/fluxible/node_modules/react-pure/src/Button.js:1
(function (exports, require, module, __filename, __dirname) { import React fro
                                                                                        ^^^^^^
 49% 21/32 build modulesSyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/stu/Projects/fluxible/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/stu/Projects/fluxible/components/Home.jsx:3:18)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/stu/Projects/fluxible/node_modules/babel/lib/babel/api/register/node.js:119:5)
```

**Comment by PaulLeCam** [comment]
Hi,

The files in `src` are written in ES6/7, they should only be accessed directly if you are using a transpiler like Babel.

You can accessed the transpiled files in `lib`, ex `require('react-pure/lib/Button')`, but the recommended way is just to use the entry file:
```js
var ReactPure = require('react-pure');
var PureButton = ReactPure.Button;
```
or directly `var PureButton = require('react-pure').Button;`

**Comment by Stubbs** [comment]
Created PR #6 to show an example of how to use them.

**Comment by PaulLeCam** [comment]
Added to https://github.com/hailocab/react-pure#usage
